### ISSUE TITLE
Non-existent config key: MODEL.BACKBONE.OUT_CHANNELS

### ISSUE THREAD

**Issue by TheFloe1995** [chengyangfu/retinamask#7]
I followed the installation instructions and everything went fine until wanted to test the pre-trained model by executing:

`python tools/test_net.py --config-file ./configs/retina/retinanet_mask_R-50-FPN_2x_adjust_std011_ms.yaml MODEL.WEIGHT ./models/retinanet_mask_R-50-FPN_2x_adjust_std011_ms_model.pth MODEL.MASK_ON False`

This leads to the following error:
```
Traceback (most recent call last):
  File "tools/test_net.py", line 100, in <module>
    main()
  File "tools/test_net.py", line 55, in main
    cfg.merge_from_file(args.config_file)
  File "/home/flo/anaconda3/envs/uav-challenge/lib/python3.6/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/home/flo/anaconda3/envs/uav-challenge/lib/python3.6/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/flo/anaconda3/envs/uav-challenge/lib/python3.6/site-packages/yacs/config.py", line 460, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/flo/anaconda3/envs/uav-challenge/lib/python3.6/site-packages/yacs/config.py", line 460, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/flo/anaconda3/envs/uav-challenge/lib/python3.6/site-packages/yacs/config.py", line 473, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.BACKBONE.OUT_CHANNELS'
```

Any ideas?

**Comment by chengyangfu** [comment]
Hi, 
    How did you install the code?  Looks like you install the different repository. 
    MODEL.BACKBONE.OUT_CHANNELS is still valid in this repository but is removed in the master branch of maskrcnn-benchmark. 
    Try to recompile the code. 
    ```
    rm -rf build
    python setup.py build develop
     ```

**Comment by TheFloe1995** [comment]
Hi,
thanks for your fast reply. I blindly followed the installation instructions and therefore completely overlooked that there is a maskrcnn_benchmark directory included in this repository along with a setup.py in the root dir.
I downloaded and installed maskrcnn_benchmark repo separately and that of course caused problems, as you pointed out.

**Comment by ahong007007** [comment]
I have the same problems.It hasn't been solved yet.

**Comment by ahong007007** [comment]
I've got the same problem, and there's no solution at this time.

**Comment by chengyangfu** [comment]
Hi @ahong007007, 
     I guess you had installed the maskrcnn-benchmark. Can you uninstall it first and try again? It will be great if you can also copy & paste the error messages.

**Comment by ahong007007** [comment]
@chengyangfu 
To Reproduce
from maskrcnn_benchmark.config import cfg
from predictor import COCODemo
import cv2
config_file = "./e2e_mask_rcnn_X_101_32x8d_FPN_1x_caffe2.yaml"
cfg.merge_from_file(config_file)
cfg.merge_from_list(["MODEL.DEVICE", "cpu"])
print(cfg)
coco_demo = COCODemo(
cfg,
min_image_size=800,
confidence_threshold=0.7,
)
def imshow(img):
plt.imshow(img[:, :, [2, 1, 0]])
plt.axis("off")
image = cv2.imread("./00019_48a40bf59425c4cea437dabe659746b0.jpg")
predictions = coco_demo.run_on_opencv_image(image)
cv2.imwrite("test.jpg",predictions)

Expected behavior
Environment
image

I just load a configuration yaml file

cfg.merge_from_file(config_file)

[environment collection script from PyTorch]
image

You can get the script and run it with:


PyTorch Version (e.g., 1.0): torch-nightly 1.0.0.dev20190312
torchvision-nightly 0.2.1

OS (e.g., Linux): Linux 2de17d7e2498 3.10.0-327

How you installed PyTorch (conda, pip, source):
pip install numpy torchvision_nightly
pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cu90/torch_nightly.html

Build command you used (if compiling from source):

Python version: py3.6

CUDA/cuDNN version: 9.0

GPU models and configuration:

Any other relevant information:

**Comment by ahong007007** [comment]
> from maskrcnn_benchmark.config import cfg
> from predictor import COCODemo
> import cv2
> config_file = "./e2e_mask_rcnn_X_101_32x8d_FPN_1x_caffe2.yaml"
> cfg.merge_from_file(config_file)
> cfg.merge_from_list(["MODEL.DEVICE", "cpu"])
> print(cfg)
> coco_demo = COCODemo(
> cfg,
> min_image_size=800,
> confidence_threshold=0.7,
> )
> def imshow(img):
> plt.imshow(img[:, :, [2, 1, 0]])
> plt.axis("off")
> image = cv2.imread("./00019_48a40bf59425c4cea437dabe659746b0.jpg")
> predictions = coco_demo.run_on_opencv_image(image)
> cv2.imwrite("test.jpg",predictions)
> 
> Expected behavior
> Environment
> image
> 
> I just load a configuration yaml file
> 
> cfg.merge_from_file(config_file)
> 

[environment collection script from PyTorch]
![image](https://user-images.githubusercontent.com/22077027/54327918-ec711600-4646-11e9-901a-0c604cb5061e.png)
I just load a configuration yaml file

> cfg.merge_from_file(config_file)

![image](https://user-images.githubusercontent.com/22077027/54327927-f72bab00-4646-11e9-9f41-7cfe60d7a59d.png)


You can get the script and run it with:


PyTorch Version (e.g., 1.0): torch-nightly 1.0.0.dev20190312
torchvision-nightly 0.2.1

OS (e.g., Linux): Linux 2de17d7e2498 3.10.0-327

How you installed PyTorch (conda, pip, source):
pip install numpy torchvision_nightly
pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cu90/torch_nightly.html

Build command you used (if compiling from source):

Python version: py3.6

CUDA/cuDNN version: 9.0

GPU models and configuration:

Any other relevant information:

**Comment by chengyangfu** [comment]
Obviously, there is a different version of maskrcnn-benchmark in your pip. You need to remove it first and then run 
``` python setup.py build develop``` 
understand the root file of retinamask.

**Comment by zardadi** [comment]
I have the same issue! I've tried to install maskrcnn_benchmark from this repo, but there is no setup.py? Could you please help me with this issue?
